# Travis build script for JNativeHook

# Use Maven
language: java

jdk:
  - openjdk8

# Using Docker to build native libraries
services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.m2
#    - docker_images

# TODO Tip do not worked as expected here
#before_install:
#  - docker load -i docker_images/images.tar || true

#before_cache:
#  - docker save -o docker_images/images.tar $(docker images -a -q)

# Set the final name using pom-fu
install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# You fill out this section by encrypting the key using the travis utility
# Note that the api_key is safe to put here because it is actually encrypted
deploy:
  provider: releases
  token:
    secure: $GITHUB_TOKEN
  file: target/release.jar
  cleanup: false
  # Modify this to build on every commit
  on:
    branch: 2.1-maven
