# Travis build script for JNativeHook

# Use new container infrastructure to enable caching
sudo: true

# Use Maven
language: java

# Using Docker to build native libraries
services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.m2

# Only re-download spigot if we don't have spigot in the repo
before_install:
  - if [ ! -d "$HOME/.m2/repository/org/spigotmc" ]; then ./installSpigot.sh 1.12 ; else echo "Not compiling Spigot because it is already in our maven" ; fi

# Set the final name using pom-fu
install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V

## You fill out this section by encrypting the key using the travis utility
## Note that the api_key is safe to put here because it is actually encrypted
#deploy:
#  provider: releases
#  api_key:
#    secure: <Your travis encrypted github release key here>
#  file: target/release.jar
#  skip_cleanup: true
#  # Modify this to build on every commit
#  on:
#    tags: true
