# Travis build script for JNativeHook
# Based on https://gist.github.com/Lazersmoke/cb8445b7bd7b113b0244fe0fae1ea7ab

os:
  - linux

dist: xenial

# Use Maven
language: java
jdk:
  - openjdk8

# Using Docker to build native libraries
services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.m2
    - $HOME/docker_images

# TODO Tip do not worked as expected here
before_install:
  - docker load -i $HOME/docker_images/images.tar || true

before_cache:
  - docker save -o $HOME/docker_images/images.tar $(docker images -a -q)

install: skip
script:
  - docker run -v $(pwd):/tmp/build -w /tmp/build peslys/jnativehook-builder:latest ant -buildfile cross.build.xml
  - mvn clean install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true

# You fill out this section by encrypting the key using the travis utility
# Note that the api_key is safe to put here because it is actually encrypted
deploy:
  provider: releases
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file: target/release.jar
  skip_cleanup: true
  on:
    tags: true
